force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/Current_Round__c.field-meta.xml
<CustomField>
    <fullName>Current_Round__c</fullName>
    <label>Current Round</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rounds</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Rounds.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>Round of 16</fullName>
    </customValue>
    <customValue>
        <fullName>Quarter Finals</fullName>
    </customValue>
    <customValue>
        <fullName>Semi Finals</fullName>
    </customValue>
    <customValue>
        <fullName>Finals</fullName>
    </customValue>
    <masterLabel>Rounds</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TournamentSelector.cls
public with sharing class TournamentSelector {

    public static Tournament__c getTournamentById(Id tournamentId) {
        return [SELECT Id, Name, Is_Completed__c, Current_Round__c FROM Tournament__c WHERE Id = :tournamentId WITH SECURITY_ENFORCED LIMIT 1];
    }

    public static List<Tournament__c> getTournaments() {
        return [SELECT Id, Name, Is_Completed__c, Current_Round__c FROM Tournament__c WITH SECURITY_ENFORCED];
    }
}