force-app/main/default/objects/Participation__c/Participation__c.object-meta.xml
<CustomObject>
    <description>Teams by tournement</description>
    <label>Participation</label>
    <nameField>
        <displayFormat>Participation-{0}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Participations</relationshipLabel>
    <relationshipName>Participations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/Current_Round__c.field-meta.xml
<CustomField>
    <fullName>Current_Round__c</fullName>
    <label>Current Round</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rounds</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Rounds.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>Round of 16</fullName>
    </customValue>
    <customValue>
        <fullName>Quarter Finals</fullName>
    </customValue>
    <customValue>
        <fullName>Semi Finals</fullName>
    </customValue>
    <customValue>
        <fullName>Finals</fullName>
    </customValue>
    <masterLabel>Rounds</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TournamentWrapper.cls
public without sharing class TournamentWrapper {

    @AuraEnabled public Id id;
    @AuraEnabled public String name;
    @AuraEnabled public String currentRound;
    @AuraEnabled public Boolean isCompleted;

    public TournamentWrapper(Tournament__c tournament) {
        this.id = tournament.Id;
        this.name = tournament.Name;
        this.currentRound = tournament.Current_Round__c;
        this.isCompleted = tournament.Is_Completed__c;
    }

    public TournamentWrapper(Participation__c participation) {
        this.id = participation.Tournament__r.Id;
        this.name = participation.Tournament__r.Name;
        this.currentRound = participation.Tournament__r.Current_Round__c;
        this.isCompleted = participation.Tournament__r.Is_Completed__c;
    }

    public static List<TournamentWrapper> buildTournamentsList(List<Tournament__c> tournaments) {
        List<TournamentWrapper> wrapper = new List<TournamentWrapper>();
        for (Tournament__c tournament : tournaments) {
            wrapper.add(new TournamentWrapper(tournament));
        }
        return wrapper;
    }

    public static List<TournamentWrapper> buildTournamentsListFromParticipations(List<Participation__c> tournaments) {
        List<TournamentWrapper> wrapper = new List<TournamentWrapper>();
        for (Participation__c tournament : tournaments) {
            wrapper.add(new TournamentWrapper(tournament));
        }
        return wrapper;
    }
}