force-app/main/default/objects/Participation__c/Participation__c.object-meta.xml
<CustomObject>
    <description>Teams by tournement</description>
    <label>Participation</label>
    <nameField>
        <displayFormat>Participation-{0}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation__c/fields/Draws__c.field-meta.xml
<CustomField>
    <fullName>Draws__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Draws</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Goals_Against__c.field-meta.xml
<CustomField>
    <fullName>Goals_Against__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Goals Against</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Goals_For__c.field-meta.xml
<CustomField>
    <fullName>Goals_For__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Goals For</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Wins__c.field-meta.xml
<CustomField>
    <fullName>Wins__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Wins</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ParticipationCompare.cls
public without sharing class ParticipationCompare implements Comparator<Participation__c> {

    // We calculate the fields (Points, GD) because Formula fields don't have a value until insert and fetched
    public Integer compare(Participation__c current, Participation__c other) {
        if (calculatePoints(current) != calculatePoints(other)) {
            return (calculatePoints(current) > calculatePoints(other)) ? -1 : 1;
        }

        if (calculateGD(current) != calculateGD(other)) {
            return (calculateGD(current) > calculateGD(other)) ? -1 : 1;
        }

        if (current.Goals_For__c != other.Goals_For__c) {
            return (current.Goals_For__c > other.Goals_For__c) ? -1 : 1;
        }

        return 0;
    }

    private static Integer calculatePoints(Participation__c participation) {
        return (Integer) ((participation.Wins__c * 3) + participation.Draws__c);
    }

    private static Integer calculateGD(Participation__c participation) {
        return (Integer) (participation.Goals_For__c - participation.Goals_Against__c);
    }
}