force-app/main/default/objects/Participation__c/Participation__c.object-meta.xml
<CustomObject>
    <description>Teams by tournement</description>
    <label>Participation</label>
    <nameField>
        <displayFormat>Participation-{0}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Participations</relationshipLabel>
    <relationshipName>Participations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stadium__c/Stadium__c.object-meta.xml
<CustomObject>
    <label>Stadium</label>
    <nameField>
        <label>Stadium Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stadiums</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/TournamentController.cls
public with sharing class TournamentController {

    @AuraEnabled(Cacheable=true)
    public static List<TournamentWrapper> getTournamentListForTeam(Id teamId) {
        Logger.info('Getting tournaments of team: ' + teamId);

        List<Participation__c> participations = ParticipationSelector.getTournamentsForParticipation(teamId);
        List<TournamentWrapper> tournaments = TournamentWrapper.buildTournamentsListFromParticipations(participations);

        Logger.saveLog();

        return tournaments;
    }

    // Setting 'Cacheable' to false because we're doing DML (otherwise DML LIMIT is set to 0)
    @AuraEnabled(Cacheable=false)
    public static Id createTournament(String tournamentTitle, Map<String, List<Id>> groupTeams, List<Stadium__c> stadiums) {
        Tournament__c tournament = TournamentService.createTournament(tournamentTitle, groupTeams, stadiums);
        return tournament.Id;
    }

    // Setting 'Cacheable' to false because we're doing DML (otherwise DML LIMIT is set to 0)
    @AuraEnabled(Cacheable=false)
    public static Boolean advanceTournament(Id tournamentId) {
        return TournamentService.advanceToNextRound(tournamentId);
    }

    // Setting 'Cacheable' to false because we're doing DML (otherwise DML LIMIT is set to 0)
    @AuraEnabled(Cacheable=false)
    public static Boolean generatePendingScores(Id tournamentId) {
        return TournamentService.generatePendingScoresForCurrentRound(tournamentId);
    }
}