force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation__c/Participation__c.object-meta.xml
<CustomObject>
    <description>Teams by tournement</description>
    <label>Participation</label>
    <nameField>
        <displayFormat>Participation-{0}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation__c/fields/Draws__c.field-meta.xml
<CustomField>
    <fullName>Draws__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Draws</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Goal_Difference__c.field-meta.xml
<CustomField>
    <fullName>Goal_Difference__c</fullName>
    <formula>Goals_For__c - Goals_Against__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Goal Difference</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Goals_Against__c.field-meta.xml
<CustomField>
    <fullName>Goals_Against__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Goals Against</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Goals_For__c.field-meta.xml
<CustomField>
    <fullName>Goals_For__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Goals For</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Losses__c.field-meta.xml
<CustomField>
    <fullName>Losses__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Losses</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Matches_Played__c.field-meta.xml
<CustomField>
    <fullName>Matches_Played__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Matches Played</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <formula>(Wins__c * 3) + Draws__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Participations</relationshipLabel>
    <relationshipName>Participations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Wins__c.field-meta.xml
<CustomField>
    <fullName>Wins__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Wins</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <label>Flag</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/StandingTeamWrapper.cls
public without sharing class StandingTeamWrapper {

    @AuraEnabled public String teamName;
    @AuraEnabled public String teamCode;
    @AuraEnabled public String teamFlag;
    @AuraEnabled public Integer matchesPlayed;
    @AuraEnabled public Integer wins;
    @AuraEnabled public Integer draws;
    @AuraEnabled public Integer losses;
    @AuraEnabled public Integer goalsFor;
    @AuraEnabled public Integer goalsAgainst;
    @AuraEnabled public Integer goalsDifference;
    @AuraEnabled public Integer points;

    public StandingTeamWrapper(Participation__c standing) {
        this.teamName = standing.Team__r.Name;
        this.teamCode = standing.Team__r.Code__c;
        this.teamFlag = standing.Team__r.Flag__c;
        this.matchesPlayed = (Integer) standing.Matches_Played__c;
        this.wins = (Integer) standing.Wins__c;
        this.draws = (Integer) standing.Draws__c;
        this.losses = (Integer) standing.Losses__c;
        this.goalsFor = (Integer) standing.Goals_For__c;
        this.goalsAgainst = (Integer) standing.Goals_Against__c;
        this.goalsDifference = (Integer) standing.Goal_Difference__c;
        this.points = (Integer) standing.Points__c;
    }

    public static Map<String, List<StandingTeamWrapper>> buildTeamsByGroups(List<Participation__c> standings) {
        standings.sort(new ParticipationCompare());
        Map<String, List<StandingTeamWrapper>> groups = new Map<String, List<StandingTeamWrapper>>();

        for (Participation__c standing : standings) {
            String groupName = standing.Group__r.Name;

            if (!groups.containsKey(standing.Group__r.Name)) {
                groups.put(groupName, new List<StandingTeamWrapper>());
            }

            groups.get(groupName).add(new StandingTeamWrapper(standing));
        }

        return groups;
    }
}