force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participation__c/Participation__c.object-meta.xml
<CustomObject>
    <description>Teams by tournement</description>
    <label>Participation</label>
    <nameField>
        <displayFormat>Participation-{0}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Participations</relationshipLabel>
    <relationshipName>Participations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/GroupController.cls
public with sharing class GroupController {

    @AuraEnabled(Cacheable=true)
    public static List<String> getGroupNames() {
        return new List<String> {'Group A', 'Group B', 'Group C', 'Group D', 'Group E', 'Group F', 'Group G', 'Group H'};
    }

    @AuraEnabled(Cacheable=true)
    public static Map<String, List<StandingTeamWrapper>> getStandings(Id tournamentId) {
        Logger.info('Getting standing for tournament: ' + tournamentId);
        List<Participation__c> participations = ParticipationSelector.getTournamentStandings(tournamentId);
        Logger.saveLog();
        return StandingTeamWrapper.buildTeamsByGroups(participations);
    }

    @AuraEnabled(Cacheable=true)
    public static Map<String, List<StandingTeamWrapper>> getStandingByTeam(Id tournamentId, Id teamId) {
        Logger.info('Getting standing for team: ' + teamId + ', part of tournament: ' + tournamentId);
        Participation__c currentTeam = ParticipationSelector.getParticipationByTournamentAndTeam(tournamentId, teamId);
        Logger.info('Getting standing for tournament: ' + currentTeam.Tournament__c + ' for group: ' + currentTeam.Group__c);
        List<Participation__c> participations = ParticipationSelector.getTournamentTeamStanding(currentTeam.Tournament__c, currentTeam.Group__c);
        Logger.saveLog();
        return StandingTeamWrapper.buildTeamsByGroups(participations);
    }
}