force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>Match-{0}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Away_Team__c.field-meta.xml
<CustomField>
    <fullName>Away_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Away Team</label>
    <referenceTo>Participation__c</referenceTo>
    <relationshipLabel>Matches (Away Team)</relationshipLabel>
    <relationshipName>Away_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Participation__c</referenceTo>
    <relationshipLabel>Matches (Home Team)</relationshipLabel>
    <relationshipName>Home_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <label>Round</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rounds</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Stadium__c.field-meta.xml
<CustomField>
    <fullName>Stadium__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stadium</label>
    <referenceTo>Stadium__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Stadium_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participation__c/Participation__c.object-meta.xml
<CustomObject>
    <description>Teams by tournement</description>
    <label>Participation</label>
    <nameField>
        <displayFormat>Participation-{0}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Participations</relationshipLabel>
    <relationshipName>Participations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Participations</relationshipLabel>
    <relationshipName>Participations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stadium__c/Stadium__c.object-meta.xml
<CustomObject>
    <label>Stadium</label>
    <nameField>
        <label>Stadium Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stadiums</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/Current_Round__c.field-meta.xml
<CustomField>
    <fullName>Current_Round__c</fullName>
    <label>Current Round</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rounds</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Rounds.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>Round of 16</fullName>
    </customValue>
    <customValue>
        <fullName>Quarter Finals</fullName>
    </customValue>
    <customValue>
        <fullName>Semi Finals</fullName>
    </customValue>
    <customValue>
        <fullName>Finals</fullName>
    </customValue>
    <masterLabel>Rounds</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TournamentGeneratorService.cls
public without sharing class TournamentGeneratorService {

    public static void generateRandomTournament(List<Team__c> teams) {
        Tournament__c tournament = TournamentDataFactory.generateTournament();
        Logger.debug('Generated tournament: ' + tournament.Name);

        List<Group__c> groups = TournamentDataFactory.generateGroups(tournament, 8);
        Logger.debug('Generated tournament groups');

        List<Stadium__c> stadiums = TournamentDataFactory.generateStadiums(8);
        Logger.debug('Generated stadiums');

        List<Participation__c> participations = setupParticipations(tournament, groups, teams);
        Logger.debug('Generated tournament participations');

        // Converting List to Map for easy access of elements
        Map<Id, Participation__c> participationsByIdsMap = new Map<Id, Participation__c>();
        for (Participation__c participation : participations) {
            participationsByIdsMap.put(participation.Id, participation);
        }

        // ALL tournament matches
        List<Match__c> matches = setupMatches(tournament, participations, stadiums);

        Logger.debug('Progressing the tournament throughout the rounds...');

        progressTournamentThroughTheGroupStage(tournament, matches, participationsByIdsMap);
        Logger.debug('Tournament is progressed to the: ROUND OF 16');

        for (String round : TournamentRounds.getKnockoutStageRoundNames()) {
            progressTournamentThroughTheKnockoutStage(tournament, matches, participationsByIdsMap);
            Logger.debug('Tournament is progressed to the: ' + round);
        }

        Logger.debug('Finished tournament generation...committing results');

        tournament.Is_Completed__c = true;

        update tournament;
        update matches;
        update participations;
    }

    private static Map<String, List<Id>> setupTeamsByGroupNameMap(List<Group__c> groups, List<Team__c> teams) {
        Map<String, List<Id>> teamsByGroup = new Map<String, List<Id>>();

        Integer maxTeamsPerGroup = teams.size() / groups.size();
        Integer currentTeamInGroupCount = 0;
        Integer currentGroupIndex = 0;

        for (Team__c team : teams) {
            if (currentTeamInGroupCount >= maxTeamsPerGroup) {
                currentGroupIndex++;
                currentTeamInGroupCount = 0;
            }

            String groupName = groups.get(currentGroupIndex).Name;
            if (!teamsByGroup.containsKey(groupName)) {
                teamsByGroup.put(groupName, new List<Id>());
            }
            teamsByGroup.get(groupName).add(team.Id);

            currentTeamInGroupCount++;
        }

        return teamsByGroup;
    }

    private static List<Participation__c> setupParticipations(Tournament__c tournament, List<Group__c> groups, List<Team__c> teams) {
        Map<String, List<Id>> teamsByGroup = setupTeamsByGroupNameMap(groups, teams);

        List<Participation__c> participations = TournamentService.setupTournament(tournament, groups, teamsByGroup);

        // Insert participations to get "real" Id
        insert participations;

        return participations;
    }


    private static List<Match__c> setupMatches(Tournament__c tournament, List<Participation__c> participations, List<Stadium__c> stadiums) {
        List<Match__c> matches = MatchService.scheduleTournamentMatches(tournament, participations, stadiums);

        // Insert matches to get "real" Id
        insert matches;

        return matches;
    }

    private static void progressTournamentThroughTheGroupStage(Tournament__c tournament, List<Match__c> matches, Map<Id, Participation__c> participationsByIdsMap) {
        tournament.Current_Round__c = TournamentRounds.toString(TournamentRounds.Round.ROUND_3);
        
        String nextRound = TournamentRounds.getNextRound(tournament.Current_Round__c);
        List<Match__c> nextRoundMatches = new List<Match__c>();

        List<Match__c> matchesToUpdate = new List<Match__c>();
        for (Match__c match : matches) {
            if (TournamentRounds.isGroupStage(match.Round__c)) {
                MatchService.generateScoresForMatch(false, match);
                matchesToUpdate.add(match);
            } else if (nextRound == match.Round__c) {
                nextRoundMatches.add(match);
            }
        }

        GroupService.updateStandings(participationsByIdsMap, matchesToUpdate);

        GroupService.updateParticipantsStatusGroupsResult(participationsByIdsMap.values());

        Boolean isFinal = TournamentRounds.isFinal(nextRound);

        MatchService.assignTeamsToMatchesForKnockoutRound(isFinal, nextRoundMatches, participationsByIdsMap.values());

        tournament.Current_Round__c = nextRound;
    }

    private static void progressTournamentThroughTheKnockoutStage(Tournament__c tournament, List<Match__c> matches, Map<Id, Participation__c> participationsByIdsMap) {
        String nextRound = TournamentRounds.getNextRound(tournament.Current_Round__c);
        List<Match__c> nextRoundMatches = new List<Match__c>();

        List<Participation__c> participationsToUpdate = new List<Participation__c>();
        List<Match__c> matchesToUpdate = new List<Match__c>();

        for (Match__c match : matches) {
            if (match.Round__c.equals(tournament.Current_Round__c)) {
                MatchService.generateScoresForMatch(true, match);
                participationsToUpdate.add(participationsByIdsMap.get(match.Home_Team__c));
                participationsToUpdate.add(participationsByIdsMap.get(match.Away_Team__c));
                matchesToUpdate.add(match);
            } else if (nextRound.equals(match.Round__c)) {
                nextRoundMatches.add(match);
            }
        }

        MatchService.updateKnockout(participationsByIdsMap, matchesToUpdate);

        Boolean isFinal = TournamentRounds.isFinal(nextRound);

        MatchService.assignTeamsToMatchesForKnockoutRound(isFinal, nextRoundMatches, participationsToUpdate);

        if (!TournamentRounds.isFinal(tournament.Current_Round__c)) {
            tournament.Current_Round__c = nextRound;
        }
    }
}