force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>Match-{0}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Away_Score__c.field-meta.xml
<CustomField>
    <fullName>Away_Score__c</fullName>
    <label>Away Team Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Away_Team__c.field-meta.xml
<CustomField>
    <fullName>Away_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Away Team</label>
    <referenceTo>Participation__c</referenceTo>
    <relationshipLabel>Matches (Away Team)</relationshipLabel>
    <relationshipName>Away_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Score__c.field-meta.xml
<CustomField>
    <fullName>Home_Score__c</fullName>
    <label>Home Team Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Participation__c</referenceTo>
    <relationshipLabel>Matches (Home Team)</relationshipLabel>
    <relationshipName>Home_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participation__c/Participation__c.object-meta.xml
<CustomObject>
    <description>Teams by tournement</description>
    <label>Participation</label>
    <nameField>
        <displayFormat>Participation-{0}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation__c/fields/Draws__c.field-meta.xml
<CustomField>
    <fullName>Draws__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Draws</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Goals_Against__c.field-meta.xml
<CustomField>
    <fullName>Goals_Against__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Goals Against</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Goals_For__c.field-meta.xml
<CustomField>
    <fullName>Goals_For__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Goals For</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Is_Eliminated__c.field-meta.xml
<CustomField>
    <fullName>Is_Eliminated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Eliminated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Losses__c.field-meta.xml
<CustomField>
    <fullName>Losses__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Losses</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Matches_Played__c.field-meta.xml
<CustomField>
    <fullName>Matches_Played__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Matches Played</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Wins__c.field-meta.xml
<CustomField>
    <fullName>Wins__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Wins</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GroupService.cls
public with sharing class GroupService {

    public static void updateStandings(Map<Id, Participation__c> participants, List<Match__c> matches) {
        Logger.info('Updating standing for matches...');
        for (Match__c match : matches) {
            Participation__c homeTeam = participants.get(match.Home_Team__c);
            Participation__c awayTeam = participants.get(match.Away_Team__c);
            if (match.Home_Score__c > match.Away_Score__c) {
                homeTeam.Wins__c++;
                awayTeam.Losses__c++;
            } else if (match.Home_Score__c < match.Away_Score__c) {
                awayTeam.Wins__c++;
                homeTeam.Losses__c++;
            } else {
                homeTeam.Draws__c++;
                awayTeam.Draws__c++;
            }
            homeTeam.Matches_Played__c++;
            homeTeam.Goals_For__c+= match.Home_Score__c;
            homeTeam.Goals_Against__c+= match.Away_Score__c;

            awayTeam.Matches_Played__c++;
            awayTeam.Goals_For__c+= match.Away_Score__c;
            awayTeam.Goals_Against__c+= match.Home_Score__c;
        }
    }
    
    public static void updateParticipantsStatusGroupsResult(List<Participation__c> participations) {
        Map<String, List<Participation__c>> participationsByGroups = new Map<String, List<Participation__c>>();

        for (Participation__c record : participations) {
            if (!participationsByGroups.containsKey(record.Group__c)) {
                participationsByGroups.put(record.Group__c, new List<SObject>());
            }
            participationsByGroups.get(record.Group__c).add(record);
        }

        for (String groupId : participationsByGroups.keySet()) {
            List<Participation__c> participationsToUpdate = participationsByGroups.get(groupId);

            // participants are sorted in an DESC order, third and forth in order are eliminated
            participationsToUpdate.sort(new ParticipationCompare());

            participationsToUpdate.get(2).Is_Eliminated__c = true;
            participationsToUpdate.get(3).Is_Eliminated__c = true;
        }

        Logger.info('Updated teams eliminated for groups stage');
    }

    public static void validateGroups(List<Participation__c> newParticipations) {
        Set<Id> groupIds = new Set<Id>();

        for (Participation__c participation : newParticipations) {
            groupIds.add(participation.Group__c);
        }

        Map<Id, Integer> teamsCountByTeam = new Map<Id, Integer>();

        for (Participation__c participation : ParticipationSelector.getParticipantsByGroups(groupIds)) {
            if (!teamsCountByTeam.containsKey(participation.Group__c)) {
                teamsCountByTeam.put(participation.Group__c, 0);
            }
            teamsCountByTeam.put(participation.Group__c, teamsCountByTeam.get(participation.Group__c) + 1);
        }

        for (Participation__c participation : newParticipations) {
            if (teamsCountByTeam.get(participation.Group__c) >= 4) {
                Logger.warn('Group for participation: ' + participation.Group__c + ' already contains 4 teams');
                participation.addError('Invalid: group already contain 4 teams');
            }
        }
    }

}