force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>Match-{0}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Away_Score__c.field-meta.xml
<CustomField>
    <fullName>Away_Score__c</fullName>
    <label>Away Team Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Score__c.field-meta.xml
<CustomField>
    <fullName>Home_Score__c</fullName>
    <label>Home Team Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MatchTriggerHandler.cls
public with sharing class MatchTriggerHandler extends TriggerHandler {

    public override void afterInsert() {
        MatchService.handleCompletedMatches(Trigger.new);
    }

    public override void afterUpdate() {
        List<Match__c> matchesToProcess = new List<Match__c>();
        Map<Id, Match__c> newMap = (Map<Id, Match__c>) Trigger.newMap;
        List<Match__c> old =  Trigger.old;
        for (Match__c match : old) {
            if (match.Away_Score__c == null && match.Home_Score__c == null) {
                matchesToProcess.add(newMap.get(match.Id));
            }
        }
        MatchService.handleCompletedMatches(matchesToProcess);
    }

    public override void beforeInsert() {
        MatchService.validateMatches(Trigger.new);
    }

    public override void beforeUpdate() {
        List<Match__c> matchesToProcess = new List<Match__c>();
        Map<Id, Match__c> oldMap = (Map<Id, Match__c>) Trigger.oldMap;
        List<Match__c> newMatches =  Trigger.new;
        for (Match__c match : newMatches) {
            // Only process matches that change groups
            if (match.Group__c != oldMap.get(match.Id).Group__c) {
                matchesToProcess.add(match);
            }
        }
        MatchService.validateMatches(matchesToProcess);
    }
}