force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participation__c/Participation__c.object-meta.xml
<CustomObject>
    <description>Teams by tournement</description>
    <label>Participation</label>
    <nameField>
        <displayFormat>Participation-{0}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation__c/fields/Draws__c.field-meta.xml
<CustomField>
    <fullName>Draws__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Draws</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Goal_Difference__c.field-meta.xml
<CustomField>
    <fullName>Goal_Difference__c</fullName>
    <formula>Goals_For__c - Goals_Against__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Goal Difference</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Goals_Against__c.field-meta.xml
<CustomField>
    <fullName>Goals_Against__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Goals Against</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Goals_For__c.field-meta.xml
<CustomField>
    <fullName>Goals_For__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Goals For</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Is_Eliminated__c.field-meta.xml
<CustomField>
    <fullName>Is_Eliminated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Eliminated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Losses__c.field-meta.xml
<CustomField>
    <fullName>Losses__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Losses</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Matches_Played__c.field-meta.xml
<CustomField>
    <fullName>Matches_Played__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Matches Played</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <formula>(Wins__c * 3) + Draws__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Participations</relationshipLabel>
    <relationshipName>Participations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Participations</relationshipLabel>
    <relationshipName>Participations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Wins__c.field-meta.xml
<CustomField>
    <fullName>Wins__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Wins</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <label>Flag</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/Current_Round__c.field-meta.xml
<CustomField>
    <fullName>Current_Round__c</fullName>
    <label>Current Round</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rounds</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Rounds.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>Round of 16</fullName>
    </customValue>
    <customValue>
        <fullName>Quarter Finals</fullName>
    </customValue>
    <customValue>
        <fullName>Semi Finals</fullName>
    </customValue>
    <customValue>
        <fullName>Finals</fullName>
    </customValue>
    <masterLabel>Rounds</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ParticipationSelector.cls
public with sharing class ParticipationSelector {

    public static List<Participation__c> getTournamentsForParticipation(Id teamId) {
        return [
                SELECT
                        Tournament__r.Id,
                        Tournament__r.Name,
                        Tournament__r.Current_Round__c,
                        Tournament__r.Is_Completed__c
                FROM Participation__c
                WHERE Team__c = :teamId
                WITH SECURITY_ENFORCED
        ];
    }

    public static List<Participation__c> getTournamentStandings(Id tournamentId) {
        return [
                SELECT
                        Id,
                        Team__r.Name,
                        Team__r.Code__c,
                        Team__r.Flag__c,
                        Group__r.Name,
                        Matches_Played__c,
                        Wins__c,
                        Draws__c,
                        Losses__c,
                        Goals_For__c,
                        Goals_Against__c,
                        Goal_Difference__c,
                        Points__c
                FROM Participation__c
                WHERE Tournament__c = :tournamentId
                WITH SECURITY_ENFORCED
                ORDER BY Points__c DESC
        ];
    }

    public static Participation__c getParticipationByTournamentAndTeam(Id tournamentId, Id teamId) {
        return [
                SELECT
                        Id,
                        Tournament__c,
                        Group__c
                FROM Participation__c
                WHERE Team__c = :teamId
                AND Tournament__c = :tournamentId
                WITH SECURITY_ENFORCED
                LIMIT 1
        ];
    }

    public static List<Participation__c> getParticipantsByTournamentTeams(Set<Id> participations) {
        return [
                SELECT
                        Id,
                        Matches_Played__c,
                        Wins__c,
                        Losses__c,
                        Draws__c,
                        Goals_For__c,
                        Goals_Against__c,
                        Points__c,
                        Group__c,
                        Is_Eliminated__c
                FROM Participation__c
                WHERE Id IN :participations
                WITH SECURITY_ENFORCED
        ];
    }

    public static List<Participation__c> getParticipantsByGroups(Set<Id> groups) {
        return [
                SELECT
                        Id,
                        Team__c,
                        Group__c
                FROM Participation__c
                WHERE Group__c IN :groups
                WITH SECURITY_ENFORCED
        ];
    }

    public static List<Participation__c> getTournamentTeamStanding(Id tournamentId, Id groupId) {
        return [
                SELECT
                        Id,
                        Team__r.Name,
                        Team__r.Code__c,
                        Team__r.Flag__c,
                        Group__r.Name,
                        Matches_Played__c,
                        Wins__c,
                        Draws__c,
                        Losses__c,
                        Goals_For__c,
                        Goals_Against__c,
                        Goal_Difference__c,
                        Points__c
                FROM Participation__c
                WHERE Tournament__c = :tournamentId
                AND Group__c =: groupId
                WITH SECURITY_ENFORCED
                ORDER BY Points__c DESC
        ];
    }
}