force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>Match-{0}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Away_Team__c.field-meta.xml
<CustomField>
    <fullName>Away_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Away Team</label>
    <referenceTo>Participation__c</referenceTo>
    <relationshipLabel>Matches (Away Team)</relationshipLabel>
    <relationshipName>Away_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Participation__c</referenceTo>
    <relationshipLabel>Matches (Home Team)</relationshipLabel>
    <relationshipName>Home_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Match_Time__c.field-meta.xml
<CustomField>
    <fullName>Match_Time__c</fullName>
    <label>Match Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <label>Round</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rounds</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participation__c/Participation__c.object-meta.xml
<CustomObject>
    <description>Teams by tournement</description>
    <label>Participation</label>
    <nameField>
        <displayFormat>Participation-{0}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Participations</relationshipLabel>
    <relationshipName>Participations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Participations</relationshipLabel>
    <relationshipName>Participations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Rounds.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>Round of 16</fullName>
    </customValue>
    <customValue>
        <fullName>Quarter Finals</fullName>
    </customValue>
    <customValue>
        <fullName>Semi Finals</fullName>
    </customValue>
    <customValue>
        <fullName>Finals</fullName>
    </customValue>
    <masterLabel>Rounds</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MatchTriggerTest.cls
@IsTest
private class MatchTriggerTest {

    @IsTest
    static void testMaxMatchesAllowedPerTeam() {
        Tournament__c tournament = TournamentDataFactory.generateTournament();
        Group__c tournamentGroup = TournamentDataFactory.generateGroup(tournament);
        List<Team__c> teams = TournamentDataFactory.generateTeams(2);
        
        List<Participation__c> participations = new List<Participation__c> {
                new Participation__c(Tournament__c = tournament.Id, Team__c = teams.get(0).Id, Group__c = tournamentGroup.Id),
                new Participation__c(Tournament__c = tournament.Id, Team__c = teams.get(1).Id, Group__c = tournamentGroup.Id)
        };

        insert participations;

        Test.startTest();

        List<Match__c> matches = new List<Match__c>();

        for (Integer i = 0; i < 3; i++) {
            matches.add(
                    new Match__c(
                            Tournament__c = tournament.Id,
                            Home_Team__c = participations.get(0).Id,
                            Away_Team__c = participations.get(1).Id,
                            Match_Time__c = System.now(),
                            Round__c = '1',
                            Group__c = tournamentGroup.Id
                    )
            );
        }

        // should pass because we schedule 3 matches for the same team
        insert matches;

        Match__c forthMatch = new Match__c(
            Tournament__c = tournament.Id,
            Home_Team__c = participations.get(0).Id,
            Away_Team__c = participations.get(1).Id,
            Match_Time__c = System.now(),
            Round__c = '1',
            Group__c = tournamentGroup.Id
        );

        try {
            insert forthMatch;
        } catch (Exception e) {
            System.assert(e.getMessage().contains('teams are already scheduled for group stage matches'));
        }

        Test.stopTest();
    }

    @IsTest
    static void testThirdMatchesAreScheduledSameTime() {
        Tournament__c tournament = TournamentDataFactory.generateTournament();
        Group__c tournamentGroup = TournamentDataFactory.generateGroup(tournament);
        List<Team__c> teams = TournamentDataFactory.generateTeams(2);
        
        List<Participation__c> participations = new List<Participation__c> {
                new Participation__c(Tournament__c = tournament.Id, Team__c = teams.get(0).Id, Group__c = tournamentGroup.Id),
                new Participation__c(Tournament__c = tournament.Id, Team__c = teams.get(1).Id, Group__c = tournamentGroup.Id)
        };

        insert participations;

        Test.startTest();

        Datetime matchTime = System.now();

        Match__c firstMatchOfThirdRound = new Match__c(
            Tournament__c = tournament.Id,
            Home_Team__c = participations.get(0).Id,
            Away_Team__c = participations.get(1).Id,
            Match_Time__c = matchTime,
            Round__c = '3',
            Group__c = tournamentGroup.Id
        );

        
        insert firstMatchOfThirdRound;

        Match__c secondMatchOfThirdRound = new Match__c(
            Tournament__c = tournament.Id,
            Home_Team__c = participations.get(0).Id,
            Away_Team__c = participations.get(1).Id,
            Match_Time__c = matchTime.addDays(1),
            Round__c = '3',
            Group__c = tournamentGroup.Id
        );

        try {
            insert secondMatchOfThirdRound;
        } catch (Exception e) {
            System.assert(e.getMessage().contains('matches of the last round should for the group be scheduled at the same time'));
        }

        Test.stopTest();
    }
}