force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>Match-{0}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Away_Score__c.field-meta.xml
<CustomField>
    <fullName>Away_Score__c</fullName>
    <label>Away Team Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Away_Team__c.field-meta.xml
<CustomField>
    <fullName>Away_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Away Team</label>
    <referenceTo>Participation__c</referenceTo>
    <relationshipLabel>Matches (Away Team)</relationshipLabel>
    <relationshipName>Away_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Score__c.field-meta.xml
<CustomField>
    <fullName>Home_Score__c</fullName>
    <label>Home Team Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Participation__c</referenceTo>
    <relationshipLabel>Matches (Home Team)</relationshipLabel>
    <relationshipName>Home_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Match_Time__c.field-meta.xml
<CustomField>
    <fullName>Match_Time__c</fullName>
    <label>Match Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <label>Round</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rounds</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Stadium__c.field-meta.xml
<CustomField>
    <fullName>Stadium__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stadium</label>
    <referenceTo>Stadium__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Stadium_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participation__c/Participation__c.object-meta.xml
<CustomObject>
    <description>Teams by tournement</description>
    <label>Participation</label>
    <nameField>
        <displayFormat>Participation-{0}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Participations</relationshipLabel>
    <relationshipName>Participations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Participations</relationshipLabel>
    <relationshipName>Participations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stadium__c/Stadium__c.object-meta.xml
<CustomObject>
    <label>Stadium</label>
    <nameField>
        <label>Stadium Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stadiums</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Rounds.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>Round of 16</fullName>
    </customValue>
    <customValue>
        <fullName>Quarter Finals</fullName>
    </customValue>
    <customValue>
        <fullName>Semi Finals</fullName>
    </customValue>
    <customValue>
        <fullName>Finals</fullName>
    </customValue>
    <masterLabel>Rounds</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MatchSelector.cls
public with sharing class MatchSelector {

    private static final Set<String> DISPLAY_FIELDS = new Set<String> {
            'Home_Team__r.Team__r.Name',
            'Home_Team__r.Team__r.Code__c',
            'Home_Team__r.Team__r.Flag__c',
            'Home_Score__c',
            'Away_Team__r.Team__r.Name',
            'Away_Team__r.Team__r.Code__c',
            'Away_Team__r.Team__r.Flag__c',
            'Away_Score__c',
            'Match_Time__c',
            'Round__c',
            'Stadium__r.Name'
    };

    public static List<Match__c> getMatchesByTeams(Set<Id> teamIds) {
        return [
                SELECT
                        Home_Team__c,
                        Away_Team__c,
                        Group__c,
                        Round__c,
                        Match_Time__c
                FROM Match__c
                WHERE (Home_Team__c IN :teamIds OR Away_Team__c IN :teamIds)
                AND Group__c != NULL
                WITH SECURITY_ENFORCED
        ];
    }

    public static List<Match__c> getUnsettledMatchesByTournamentAndRound(Id tournamentId, String round) {
        return [
                SELECT
                        Id,
                        Home_Team__c,
                        Home_Score__c,
                        Away_Team__c,
                        Away_Score__c
                FROM Match__c
                WHERE Round__c = :round
                AND Tournament__c = :tournamentId
                AND (Home_Score__c = NULL AND Away_Score__c = NULL)
                WITH SECURITY_ENFORCED
        ];
    }

    public static List<Match__c> getMatchesByTournamentAndRounds(Id tournamentId, Set<String> rounds) {
        return [
                SELECT
                        Home_Team__c,
                        Home_Score__c,
                        Away_Team__c,
                        Away_Score__c,
                        Round__c
                FROM Match__c
                WHERE Tournament__c = :tournamentId AND Round__c = : rounds
                WITH SECURITY_ENFORCED
        ];
    }

    public static List<Match__c> getUpcomingMatchesByTeam(Id tournamentId, Id teamId) {
        return Database.query('SELECT ' + String.join(DISPLAY_FIELDS, ',') +
                ' FROM Match__c' +
                ' WHERE Tournament__c = :tournamentId' +
                ' AND (Home_Team__c = :teamId OR Away_Team__c = :teamId)' +
                ' AND (Home_Score__c = NULL AND Away_Score__c = NULL)' +
                ' WITH SECURITY_ENFORCED' +
                ' ORDER BY Match_Time__c ASC' +
                ' LIMIT 3'
        );
    }

    public static List<Match__c> getRecentMatchesByTeam(Id tournamentId, Id teamId) {
        return Database.query('SELECT ' + String.join(DISPLAY_FIELDS, ',') +
                ' FROM Match__c' +
                ' WHERE Tournament__c = :tournamentId' +
                ' AND (Home_Team__c = :teamId OR Away_Team__c = :teamId)' +
                ' AND (Home_Score__c <> NULL AND Away_Score__c <> NULL)' +
                ' WITH SECURITY_ENFORCED' +
                ' ORDER BY Match_Time__c DESC' +
                ' LIMIT 3'
        );
    }

    public static List<Match__c> getMatchesByRoundsAndTeam(Id tournamentId, Id participationId, List<String> rounds) {
        return Database.query('SELECT ' + String.join(DISPLAY_FIELDS, ',') +
                ' FROM Match__c' +
                ' WHERE Tournament__c = :tournamentId' +
                ' AND Round__c IN :rounds' +
                ' AND (Home_Team__c = :participationId OR Away_Team__c = :participationId)' +
                ' WITH SECURITY_ENFORCED' +
                ' ORDER BY Match_Time__c ASC'
        );
    }

    public static List<Match__c> getMatchesByTournamentAndRounds(Id tournamentId, List<String> round) {
        return Database.query('SELECT ' + String.join(DISPLAY_FIELDS, ',') +
                ' FROM Match__c' +
                ' WHERE Tournament__c = :tournamentId' +
                ' AND Round__c IN :round' +
                ' WITH SECURITY_ENFORCED' +
                ' ORDER BY Match_Time__c ASC'
        );
    }

    public static List<Match__c> getMatchesByTournament(Id tournamentId) {
        return Database.query('SELECT ' + String.join(DISPLAY_FIELDS, ',') +
                ' FROM Match__c' +
                ' WHERE Tournament__c = :tournamentId' +
                ' WITH SECURITY_ENFORCED'
        );
    }
}