force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>Match-{0}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Away_Score__c.field-meta.xml
<CustomField>
    <fullName>Away_Score__c</fullName>
    <label>Away Team Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Away_Team__c.field-meta.xml
<CustomField>
    <fullName>Away_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Away Team</label>
    <referenceTo>Participation__c</referenceTo>
    <relationshipLabel>Matches (Away Team)</relationshipLabel>
    <relationshipName>Away_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Score__c.field-meta.xml
<CustomField>
    <fullName>Home_Score__c</fullName>
    <label>Home Team Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Participation__c</referenceTo>
    <relationshipLabel>Matches (Home Team)</relationshipLabel>
    <relationshipName>Home_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <label>Round</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rounds</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Stadium__c.field-meta.xml
<CustomField>
    <fullName>Stadium__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stadium</label>
    <referenceTo>Stadium__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Stadium_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participation__c/Participation__c.object-meta.xml
<CustomObject>
    <description>Teams by tournement</description>
    <label>Participation</label>
    <nameField>
        <displayFormat>Participation-{0}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation__c/fields/Draws__c.field-meta.xml
<CustomField>
    <fullName>Draws__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Draws</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Goals_Against__c.field-meta.xml
<CustomField>
    <fullName>Goals_Against__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Goals Against</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Goals_For__c.field-meta.xml
<CustomField>
    <fullName>Goals_For__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Goals For</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Losses__c.field-meta.xml
<CustomField>
    <fullName>Losses__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Losses</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Matches_Played__c.field-meta.xml
<CustomField>
    <fullName>Matches_Played__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Matches Played</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Participations</relationshipLabel>
    <relationshipName>Participations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Participations</relationshipLabel>
    <relationshipName>Participations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Wins__c.field-meta.xml
<CustomField>
    <fullName>Wins__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Wins</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stadium__c/Stadium__c.object-meta.xml
<CustomObject>
    <label>Stadium</label>
    <nameField>
        <label>Stadium Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stadiums</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/Current_Round__c.field-meta.xml
<CustomField>
    <fullName>Current_Round__c</fullName>
    <label>Current Round</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rounds</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Rounds.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>Round of 16</fullName>
    </customValue>
    <customValue>
        <fullName>Quarter Finals</fullName>
    </customValue>
    <customValue>
        <fullName>Semi Finals</fullName>
    </customValue>
    <customValue>
        <fullName>Finals</fullName>
    </customValue>
    <masterLabel>Rounds</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TournamentService.cls
public with sharing class TournamentService {

    public static Tournament__c createTournament(String tournamentTitle, Map<String, List<Id>> groupTeams, List<Stadium__c> stadiums) {
        Tournament__c tournament = new Tournament__c(Name = tournamentTitle, Current_Round__c = '1');

        // Insert tournament to get "real" Id
        insert tournament;

        Logger.info('Persisted tournament: ' + tournament.Id);

        List<Group__c> groups = new List<Group__c>();

        for (String groupName : groupTeams.keySet()) {
            groups.add(new Group__c(
                    Name = groupName,
                    Tournament__c = tournament.Id
            ));
        }

        // Insert groups to get "real" Id
        insert groups;

        Logger.info('Persisted groups for tournament: ' + tournament.Id);

        List<Participation__c> participations = setupTournament(tournament, groups, groupTeams);

        // Insert participations to get "real" Id
        insert participations;

        List<Match__c> matches = MatchService.scheduleTournamentMatches(tournament, participations, stadiums);

        insert matches;

        Logger.saveLog();

        return tournament;
    }

    public static List<Participation__c> setupTournament(Tournament__c tournament, List<Group__c> groups, Map<String, List<Id>> groupTeams) {
        List<Participation__c> participations = new List<Participation__c>();

        // Map to store group Ids by group name since from the request we identify teams by group names and not Ids
        Map<String, Id> groupNamesToIds = new Map<String, Id>();
        for (Group__c groupRecord : groups) {
            groupNamesToIds.put(groupRecord.Name, groupRecord.Id);
        }

        for (String groupName : groupTeams.keySet()) {
            Id groupId = groupNamesToIds.get(groupName);
            List<Id> teams = groupTeams.get(groupName);

            for (Id team : teams) {
                participations.add(new Participation__c(
                        Tournament__c = tournament.Id,
                        Group__c = groupId,
                        Team__c = team,
                        Draws__c = 0,
                        Wins__c = 0,
                        Losses__c = 0,
                        Goals_For__c = 0,
                        Goals_Against__c = 0,
                        Matches_Played__c = 0
                ));
            }
        }

        Logger.debug('Completed setup of participations for tournament: ' + tournament.Id);

        return participations;
    }

    public static Boolean generatePendingScoresForCurrentRound(Id tournamentId) {
        Logger.info('Generating score for pending matches for tournament : ' + tournamentId);
        Tournament__c tournament = TournamentSelector.getTournamentById(tournamentId);
        List<Match__c> matches = MatchSelector.getUnsettledMatchesByTournamentAndRound(tournament.Id, tournament.Current_Round__c);
        Boolean enforceWinner = TournamentRounds.isKnockoutStage(tournament.Current_Round__c);

        MatchService.randomizeMatchesScores(enforceWinner, matches);

        if (!matches.isEmpty()) {
            if (TournamentRounds.isFinal(tournament.Current_Round__c)) {
                Logger.info('Setting tournament: ' + tournamentId + ' to completed, no matches left to update');
                tournament.Is_Completed__c = true;
            }
            update matches;
            update tournament;
        }

        Logger.saveLog();

        return matches.isEmpty();
    }

    public static Boolean advanceToNextRound(Id tournamentId) {
        Logger.info('Advancing to the next round for tournament : ' + tournamentId);
        Tournament__c tournament = TournamentSelector.getTournamentById(tournamentId);

        // Tournament is completed, returning false to notify that no changes has been done
        if (tournament.Is_Completed__c) {
            Logger.info('Tournament is already completed : ' + tournamentId);
            return false;
        }

        String nextRound = TournamentRounds.getNextRound(tournament.Current_Round__c);

        Boolean isFinalRoundNext = TournamentRounds.isFinal(nextRound);

        List<Match__c> matches = MatchSelector.getMatchesByTournamentAndRounds(tournament.Id, new Set<String> {tournament.Current_Round__c, nextRound});

        List<Match__c> matchesForNextRound = new List<Match__c>();

        Set<Id> participantsIds = new Set<Id>();
        for (Match__c match : matches) {
            if (match.Round__c == nextRound) {
                matchesForNextRound.add(match);
            } else {
                if (match.Home_Score__c == null || match.Away_Score__c == null) {
                    Logger.error('Cannot progress tournament: ' + tournamentId + ' with unsettled matches');
                    throw new AuraHandledException('Cannot progress to next round, please settle the scores for the matches first');
                }
                participantsIds.add(match.Home_Team__c);
                participantsIds.add(match.Away_Team__c);
            }
        }

        List<Participation__c> participations = ParticipationSelector.getParticipantsByTournamentTeams(participantsIds);

        if (TournamentRounds.isGroupStage(tournament.Current_Round__c) && TournamentRounds.isKnockoutStage(nextRound)) {
            GroupService.updateParticipantsStatusGroupsResult(participations);
            MatchService.updateMatchesForKnockoutRound(isFinalRoundNext, matchesForNextRound, participations);
        }

        if (TournamentRounds.isKnockoutStage(tournament.Current_Round__c)) {
            MatchService.updateMatchesForKnockoutRound(isFinalRoundNext, matchesForNextRound, participations);
        }

        update participations;

        tournament.Current_Round__c = nextRound;

        update tournament;

        Logger.info('Advanced tournament: ' + tournamentId + 'to :' + nextRound);
        Logger.saveLog();

        return true;
    }
}