force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation__c/Participation__c.object-meta.xml
<CustomObject>
    <description>Teams by tournement</description>
    <label>Participation</label>
    <nameField>
        <displayFormat>Participation-{0}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ParticipationTriggerHandler.cls
public with sharing class ParticipationTriggerHandler extends TriggerHandler {

    public override void beforeInsert() {
        GroupService.validateGroups(Trigger.new);
    }

    public override void beforeUpdate() {
        List<Participation__c> participationsToProcess = new List<Participation__c>();
        Map<Id, Participation__c> oldMap = (Map<Id, Participation__c>) Trigger.oldMap;
        List<Participation__c> newParticipations =  Trigger.new;
        for (Participation__c participation : newParticipations) {
            // Process only participations that change groups
            if (participation.Group__c != oldMap.get(participation.Id).Group__c) {
                participationsToProcess.add(participation);
            }
        }
        GroupService.validateGroups(participationsToProcess);
    }
}