force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>Match-{0}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Away_Score__c.field-meta.xml
<CustomField>
    <fullName>Away_Score__c</fullName>
    <label>Away Team Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Away_Team__c.field-meta.xml
<CustomField>
    <fullName>Away_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Away Team</label>
    <referenceTo>Participation__c</referenceTo>
    <relationshipLabel>Matches (Away Team)</relationshipLabel>
    <relationshipName>Away_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Score__c.field-meta.xml
<CustomField>
    <fullName>Home_Score__c</fullName>
    <label>Home Team Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Participation__c</referenceTo>
    <relationshipLabel>Matches (Home Team)</relationshipLabel>
    <relationshipName>Home_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Match_Time__c.field-meta.xml
<CustomField>
    <fullName>Match_Time__c</fullName>
    <label>Match Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <label>Round</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rounds</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Stadium__c.field-meta.xml
<CustomField>
    <fullName>Stadium__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stadium</label>
    <referenceTo>Stadium__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Stadium_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participation__c/Participation__c.object-meta.xml
<CustomObject>
    <description>Teams by tournement</description>
    <label>Participation</label>
    <nameField>
        <displayFormat>Participation-{0}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Is_Eliminated__c.field-meta.xml
<CustomField>
    <fullName>Is_Eliminated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Eliminated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participation__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Participations</relationshipLabel>
    <relationshipName>Participations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stadium__c/Stadium__c.object-meta.xml
<CustomObject>
    <label>Stadium</label>
    <nameField>
        <label>Stadium Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stadiums</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Rounds.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>Round of 16</fullName>
    </customValue>
    <customValue>
        <fullName>Quarter Finals</fullName>
    </customValue>
    <customValue>
        <fullName>Semi Finals</fullName>
    </customValue>
    <customValue>
        <fullName>Finals</fullName>
    </customValue>
    <masterLabel>Rounds</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MatchService.cls
public with sharing class MatchService {

    public static void validateMatches(List<Match__c> matchesToSchedule) {
        Set<Id> teamIds = new Set<Id>();
        for (Match__c match : matchesToSchedule) {
            teamIds.add(match.Away_Team__c);
            teamIds.add(match.Home_Team__c);
        }
        List<Match__c> scheduledMatches = MatchSelector.getMatchesByTeams(teamIds);

        Map<Id, Integer> matchesPerTeam = new Map<Id, Integer>();
        Map<Id, Match__c> thirdRoundMatchesPerGroup = new Map<Id, Match__c>();

        for (Match__c match : scheduledMatches) {
            incrementMatchCountInMap(matchesPerTeam, match.Home_Team__c);
            incrementMatchCountInMap(matchesPerTeam, match.Away_Team__c);

            if (TournamentRounds.isThirdRound(match.Round__c)) {
                thirdRoundMatchesPerGroup.put(match.Group__c, match);
            }
        }

        for (Match__c match : matchesToSchedule) {
            Integer homeMatchesCount = matchesPerTeam.get(match.Home_Team__c);
            Integer awayMatchesCount = matchesPerTeam.get(match.Away_Team__c);

            if (homeMatchesCount >= 3 || awayMatchesCount >= 3) {
                Logger.warn('Teams to process are already scheduled for group stage matches');
                match.addError('Invalid: teams are already scheduled for group stage matches');
            } else {
                if (TournamentRounds.isThirdRound(match.Round__c)) {
                    Match__c existingThirdMatch = thirdRoundMatchesPerGroup.get(match.Group__c);
                    if (existingThirdMatch != null && existingThirdMatch.Match_Time__c != match.Match_Time__c) {
                        Logger.warn('Matches of the last round should for the group be scheduled at the same time');
                        match.addError('Invalid: matches of the last round should for the group be scheduled at the same time');
                    }
                }
            }
        }
        Logger.saveLog();
    }
    
    public static void handleCompletedMatches(List<Match__c> matches) {
        Set<Id> participations = new Set<Id>();
        List<Match__c> groupStageMatches = new List<Match__c>();
        List<Match__c> knockoutStageMatches = new List<Match__c>();

        for (Match__c match : matches) {
            if (match.Home_Score__c == null || match.Away_Score__c == null) {
                continue;
            }
            participations.add(match.Home_Team__c);
            participations.add(match.Away_Team__c);
            if (TournamentRounds.isGroupStage(match.Round__c)) {
                groupStageMatches.add(match);
            } else {
                knockoutStageMatches.add(match);
            }
        }

        Map<Id, Participation__c> participants = new Map<Id, Participation__c>(
                ParticipationSelector.getParticipantsByTournamentTeams(participations)
        );

        if (!groupStageMatches.isEmpty()) {
            Logger.debug('Group stage matches found, updating standings...');
            GroupService.updateStandings(participants, groupStageMatches);
        }

        if (!knockoutStageMatches.isEmpty()) {
            Logger.debug('Knockout stage matches found, updating eliminations...');
            updateKnockout(participants, knockoutStageMatches);
        }

        if (!participants.values().isEmpty()) {
            update participants.values();
        }

        Logger.saveLog();
    }

    public static List<Match__c> scheduleTournamentMatches(Tournament__c tournament, List<Participation__c> participations, List<Stadium__c> stadiums) {
        List<Match__c> matches = new List<Match__c>();

        Logger.info('Scheduling matches for tournament: ' + tournament.Id);

        ScheduleHelper scheduler = new ScheduleHelper(System.now());

        matches.addAll(generateGroupStageMatches(tournament, participations, scheduler, stadiums));
        Logger.debug('Scheduled group stage matches for tournament: ' + tournament.Id);

        matches.addAll(generateKnockoutStageMatches(tournament, 'Round of 16', 8, scheduler, stadiums));
        Logger.debug('Scheduled Round of 16 matches for tournament: ' + tournament.Id);

        matches.addAll(generateKnockoutStageMatches(tournament, 'Quarter Finals', 4, scheduler, stadiums));
        Logger.debug('Scheduled Quarter Finals matches for tournament: ' + tournament.Id);

        matches.addAll(generateKnockoutStageMatches(tournament, 'Semi Finals', 2, scheduler, stadiums));
        Logger.debug('Scheduled Semi Finals matches for tournament: ' + tournament.Id);

        matches.addAll(generateKnockoutStageMatches(tournament, 'Finals', 2, scheduler, stadiums));
        Logger.debug('Scheduled Finals matches for tournament: ' + tournament.Id);

        return matches;
    }

    public static List<Match__c> generateGroupStageMatches(Tournament__c tournament, List<Participation__c> participations, ScheduleHelper scheduler, List<Stadium__c> stadiums) {
        List<Match__c> matches = new List<Match__c>();
        List<List<Integer>> combinations = new List<List<Integer>> {
                new List<Integer> {0, 1, 2, 3},
                new List<Integer> {0, 2, 1, 3},
                new List<Integer> {0, 3, 1, 2}
        };

        Map<Id ,List<Id>> groups = new Map<Id, List<Id>>();

        for (Participation__c participation: participations) {
            if (!groups.containsKey(participation.Group__c)) {
                groups.put(participation.Group__c, new List<Id>());
            }
            groups.get(participation.Group__c).add(participation.Id);
        }

        List<String> rounds = TournamentRounds.getGroupStageRoundNames();

        for (Id groupId : groups.keySet()) {
            List<Id> teams = groups.get(groupId);
            for (Integer i = 0; i < combinations.size(); i++) {
                Datetime matchTime = scheduler.getNextSchedule();
                for (Integer j = 0; j < combinations[i].size(); j += 2) {
                    Integer homeTeamPosition = combinations[i][j];
                    Integer awayTeamPosition = combinations[i][j + 1];
                    matches.add(
                            new Match__c(
                                    Home_Team__c = teams.get(homeTeamPosition),
                                    Away_Team__c = teams.get(awayTeamPosition),
                                    Group__c = groupId,
                                    Round__c = rounds.get(i),
                                    Tournament__c = tournament.Id,
                                    Match_Time__c = matchTime,
                                    Stadium__c = getRandomStadium(stadiums).Id
                            )
                    );
                }
            }
        }
        return matches;
    }

    public static List<Match__c> generateKnockoutStageMatches(Tournament__c tournament, String roundName, Integer matchCount, ScheduleHelper scheduler, List<Stadium__c> stadiums) {
        List<Match__c> matches = new List<Match__c>();
        for (Integer i = 0; i < matchCount; i++) {
            matches.add(new Match__c(
                    Tournament__c = tournament.Id,
                    Round__c = roundName,
                    Match_Time__c = scheduler.getNextSchedule(),
                    Stadium__c = getRandomStadium(stadiums).Id
            ));
        }

        return matches;
    }

    public static void updateKnockout(Map<Id, Participation__c> participants, List<Match__c> matches) {
        for (Match__c match : matches) {
            Participation__c homeTeam = participants.get(match.Home_Team__c);
            Participation__c awayTeam = participants.get(match.Away_Team__c);
            if (match.Home_Score__c > match.Away_Score__c) {
                awayTeam.Is_Eliminated__c = true;
            } else {
                homeTeam.Is_Eliminated__c = true;
            }
        }
    }

    public static void updateMatchesForKnockoutRound(Boolean isFinalRoundNext, List<Match__c> matches, List<Participation__c> participations) {
        assignTeamsToMatchesForKnockoutRound(isFinalRoundNext, matches, participations);
        update matches;
    }

    public static List<Match__c> assignTeamsToMatchesForKnockoutRound(Boolean isFinalRoundNext, List<Match__c> matches, List<Participation__c> participations) {
        List<Participation__c> winners = new List<Participation__c>();
        List<Participation__c> losers = new List<Participation__c>();

        List<Participation__c> participationsToConsider = new List<Participation__c>();

        for (Participation__c participation : participations) {
            if (participation.Is_Eliminated__c == false) {
                winners.add(participation);
            } else {
                losers.add(participation);
            }
        }

        if (isFinalRoundNext) {
            participationsToConsider.addAll(losers);
        }

        participationsToConsider.addAll(winners);

        for (Integer i = 0; i < matches.size(); i++) {
            matches.get(i).Home_Team__c = participationsToConsider.get(i * 2).Id;
            matches.get(i).Away_Team__c = participationsToConsider.get((i * 2)+ 1).Id;
        }

        return matches;
    }

    public static List<Match__c> randomizeMatchesScores(Boolean enforceWinner, List<Match__c> matches) {
        for (Match__c match : matches) {
            generateScoresForMatch(enforceWinner, match);
        }
        return matches;
    }

    public static void generateScoresForMatch(Boolean enforceWinner, Match__c match) {
        Integer homeScore = generateScore();
        Integer awayScore = generateScore();

        // Enforce a winner, in Knockout stage we can't have teams end on a draw
        if (enforceWinner) {
            while (homeScore == awayScore) {
                homeScore = generateScore();
                awayScore = generateScore();
            }
        }

        match.Home_Score__c = homeScore;
        match.Away_Score__c = awayScore;
    }

    private static Integer generateScore() {
        return Math.round(Math.random() * 10);
    }

    private static Stadium__c getRandomStadium(List<Stadium__c> stadiums) {
        Integer position = Integer.valueOf(Math.random() * stadiums.size());
        return stadiums.get(position);
    }

    private static void incrementMatchCountInMap(Map<Id, Integer> matchesPerTeam, Id teamId) {
        if (!matchesPerTeam.containsKey(teamId)) {
            matchesPerTeam.put(teamId, 0);
        }
        matchesPerTeam.put(teamId, matchesPerTeam.get(teamId) + 1);
    }
}