force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stadium__c/Stadium__c.object-meta.xml
<CustomObject>
    <label>Stadium</label>
    <nameField>
        <label>Stadium Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stadiums</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <label>Flag</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/TournamentDataFactory.cls
public without sharing class TournamentDataFactory {
    
    public static Tournament__c generateTournament() {
        Tournament__c tournament = new Tournament__c(Name = 'Tournament ' + System.now().toString());

        // Insert tournament to get "real" Id
        insert tournament;

        return tournament;
    }

    public static List<Team__c> generateTeams(Integer count) {
        List<Team__c> teams = new List<Team__c>();

        for (Integer i = 1; i <= count; i++) {
            String teamName = 'Team ' + i;
            teams.add(new Team__c(Name = teamName, Flag__c = 'https://flagcdn.com/un.svg', Code__c = i.toString()));
        }

        // Insert teams to get "real" Id
        insert teams;

        return teams;
    }

    public static List<Stadium__c> generateStadiums(Integer count) {
        List<Stadium__c> stadiums = new List<Stadium__c>();

        for (Integer i = 1; i <= count; i++) {
            String stadiumName = 'Stadium ' + i;
            stadiums.add(new Stadium__c(Name=stadiumName, Country__c='Country'));
        }

        // Insert stadiums to get "real" Id
        insert stadiums;

        return stadiums;
    }

    public static Group__c generateGroup(Tournament__c tournament) {
        Group__c tournamentGroup = new Group__c(Name = 'Group', Tournament__c = tournament.Id);

        // Insert group to get "real" Id
        insert tournamentGroup;

        return tournamentGroup;
    }

    public static List<Group__c> generateGroups(Tournament__c tournament, Integer count) {
        List<Group__c> groups = new List<Group__c>();

        for (Integer i = 1; i <= count; i++) {
            String groupName = 'Group ' + i;
            groups.add(new Group__c(Name = groupName, Tournament__c = tournament.Id));
        }

        // Insert groups to get "real" Id
        insert groups;

        return groups;
    }
}