force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>Match-{0}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation__c/Participation__c.object-meta.xml
<CustomObject>
    <description>Teams by tournement</description>
    <label>Participation</label>
    <nameField>
        <displayFormat>Participation-{0}</displayFormat>
        <label>Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participation__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Participations</relationshipLabel>
    <relationshipName>Participations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/MatchController.cls
public with sharing class MatchController {

    @AuraEnabled(Cacheable=true)
    public static List<MatchWrapper> getRecentMatchesByTeam(Id tournamentId, Id teamId) {
        Logger.info('Getting recent matches for team: ' + teamId + ', part of tournament: ' + tournamentId);
        Id participationId = ParticipationSelector.getParticipationByTournamentAndTeam(tournamentId, teamId).Id;
        List<Match__c> matches = MatchSelector.getRecentMatchesByTeam(tournamentId, participationId);
        Logger.saveLog();
        return MatchWrapper.buildMatchesList(matches);
    }

    @AuraEnabled(Cacheable=true)
    public static List<MatchWrapper> getUpcomingMatchesByTeam(Id tournamentId, Id teamId) {
        Logger.info('Getting upcoming matches for team: ' + teamId + ', part of tournament: ' + tournamentId);
        Id participationId = ParticipationSelector.getParticipationByTournamentAndTeam(tournamentId, teamId).Id;
        List<Match__c> matches = MatchSelector.getUpcomingMatchesByTeam(tournamentId, participationId);
        Logger.saveLog();
        return MatchWrapper.buildMatchesList(matches);
    }

    @AuraEnabled(Cacheable=true)
    public static List<MatchWrapper> getKnockoutStageMatches(Id tournamentId, Id teamId) {
        List<String> knockoutRounds = TournamentRounds.getKnockoutStageRoundNames();

        List<Match__c> matches = new List<Match__c>();

        if (teamId != null) {
            Participation__c participation = ParticipationSelector.getParticipationByTournamentAndTeam(tournamentId, teamId);
            Logger.info('Getting knockout matches for team: ' + participation.Id + ', part of tournament: ' + participation.Tournament__c);
            matches = MatchSelector.getMatchesByRoundsAndTeam(participation.Tournament__c, participation.Id, knockoutRounds);
        } else {
            Logger.info('Getting knockout matches for tournament: ' + tournamentId);
            matches = MatchSelector.getMatchesByTournamentAndRounds(tournamentId, knockoutRounds);
        }

        Logger.saveLog();
        return MatchWrapper.buildMatchesList(matches);
    }
}